server {
    listen 80 default_server;
    server_name _;

    root /etc/nginx/html;
    index index.html;

    location = /index.html {
        ssi on;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
